In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [75]:
Cryotheraphy = pd.read_csv("Cryotherapy3.csv")

In [76]:
Cryotheraphy.head()

sex  age   Time  Number_of_Warts  Type  Area  Result_of_Treatment
0    1   35  12.00                5     1   100                    0
1    1   29   7.00                5     1    96                    1
2    1   50   8.00                1     3   132                    0
3    1   32  11.75                7     3   750                    0
4    1   67   9.25                1     1    42                    0

In [77]:
Cryotheraphy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   sex                  90 non-null     int64  
 1   age                  90 non-null     int64  
 2   Time                 90 non-null     float64
 3   Number_of_Warts      90 non-null     int64  
 4   Type                 90 non-null     int64  
 5   Area                 90 non-null     int64  
 6   Result_of_Treatment  90 non-null     int64  
dtypes: float64(1), int64(6)
memory usage: 5.0 KB


In [78]:
# Variabel Independen
x = Cryotheraphy.drop(["Result_of_Treatment"], axis = 1)
x.head()

sex  age   Time  Number_of_Warts  Type  Area
0    1   35  12.00                5     1   100
1    1   29   7.00                5     1    96
2    1   50   8.00                1     3   132
3    1   32  11.75                7     3   750
4    1   67   9.25                1     1    42

In [79]:
# Variabel Dependen
y = Cryotheraphy["Result_of_Treatment"]
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Result_of_Treatment, dtype: int64

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [82]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)  
x_test = scaler.transform(x_test)

In [83]:
from sklearn.neighbors import KNeighborsClassifier

In [84]:
# Mengaktifkan fungsi klasifikasi
klasifikasi = KNeighborsClassifier(n_neighbors=5)

In [85]:
# Memasukkan data training pada fungsi klasifikasi
klasifikasi.fit(x_train, y_train)

KNeighborsClassifier()

In [86]:
# Menentukan hasil prediksi dari x_test
y_pred = klasifikasi.predict(x_test)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0])

In [87]:
# Menentukan probabilitas hasil prediksi
klasifikasi.predict_proba(x_test)

array([[0.6, 0.4],
       [0.8, 0.2],
       [0.6, 0.4],
       [0.2, 0.8],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0.6, 0.4],
       [0. , 1. ],
       [0. , 1. ],
       [0.6, 0.4],
       [0.8, 0.2],
       [0. , 1. ],
       [0.8, 0.2],
       [0. , 1. ],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.6, 0.4]])

In [88]:
from sklearn.metrics import classification_report, confusion_matrix

In [89]:
print(confusion_matrix(y_test, y_pred))

[[9 0]
 [1 8]]


In [90]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95         9
           1       1.00      0.89      0.94         9

    accuracy                           0.94        18
   macro avg       0.95      0.94      0.94        18
weighted avg       0.95      0.94      0.94        18



In [92]:
#nilai akurasi
from sklearn.metrics import accuracy_score
accuracy= accuracy_score(y_test, y_pred)
accuracy

0.9444444444444444